# Generated by Django 3.1.5 on 2021-02-03 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='media/company-logo')),
            ],
            options={
                'verbose_name': 'Car Company',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_name', models.CharField(max_length=50, unique=True)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcompany')),
            ],
            options={
                'verbose_name': 'Car Model',
                'ordering': ['car_model_name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'city',
                'ordering': ('city_name',),
            },
        ),
        migrations.CreateModel(
            name='CarVarient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Varient_name', models.CharField(max_length=50, unique=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_driven', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('fuel_type', models.CharField(choices=[('p', 'Petrol'), ('d', 'Deisel'), ('g', 'Gas')], default='p', max_length=1)),
                ('transmission_type', models.CharField(choices=[('m', 'manual'), ('a', 'automatic')], default='m', max_length=1)),
                ('reg_year', models.CharField(choices=[('a', '2010'), ('b', '2011'), ('c', '2012'), ('d', '2013'), ('e', '2014'), ('f', '2015'), ('g', '2016'), ('h', '2017'), ('i', '2018'), ('j', '2019'), ('k', '2020'), ('l', '2021')], default='l', max_length=1)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('car_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carvarient')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.city')),
            ],
        ),
    ]
