# Generated by Django 3.1.5 on 2021-02-04 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['car_company', 'car_model_name'], 'verbose_name': 'Car Model'},
        ),
        migrations.AlterModelOptions(
            name='carvarient',
            options={'ordering': ('car_model__car_company', 'car_model__car_model_name')},
        ),
        migrations.AddField(
            model_name='carinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinstance',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
