# Generated by Django 3.1.5 on 2021-02-15 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_auto_20210204_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinstance',
            options={'ordering': ['created_at', 'city', 'car_model__car_company', 'car_model__car_model_name']},
        ),
        migrations.AddField(
            model_name='carinstance',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='image',
            field=models.ImageField(upload_to='media/car-image'),
        ),
    ]
