# Generated by Django 3.1.5 on 2021-02-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_system', '0001_initial'),
        ('cars', '0004_remove_carinstance_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinstance',
            name='id',
        ),
        migrations.AddField(
            model_name='carinstance',
            name='likestarget_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='like_system.likestarget'),
            preserve_default=False,
        ),
    ]
