# Generated by Django 3.1.5 on 2021-02-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210215_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=2),
            preserve_default=False,
        ),
    ]
