# Generated by Django 3.1.5 on 2021-02-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carinstance_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
