# Generated by Django 3.1.5 on 2021-03-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carinstance_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='mileage',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
