# Generated by Django 3.1.5 on 2021-02-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bank',
            field=models.BooleanField(default=False),
        ),
    ]
