# Generated by Django 3.1.5 on 2021-02-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20210217_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninstance',
            name='income_proof',
            field=models.ImageField(upload_to='media/loan-document'),
        ),
    ]
