# Generated by Django 3.1.5 on 2021-02-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20210218_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstance',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
